### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by t2wu** [kapetan/cordova-plugin-android-wifi-manager#4]
Cordova WifiManager 1.0.0.

Crash log:

03-23 12:13:15.311 2782-2782/com.xxxxx.xxxxx E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.xxxxx.xxxxx, PID: 2782
java.lang.RuntimeException: Unable to pause activity {com.xxxxx.xxxxx/com.xxxxx.xxxxx.MainActivity}: java.lang.IllegalA
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4599)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4558)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4533)
at android.app.ActivityThread.access$1300(ActivityThread.java:222)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7237)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: dk.kapetanovic.wifimanager.WifiManagerPlugin$WifiBroadcastReceiver@d7
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:878)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1279)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:601)
at dk.kapetanovic.wifimanager.WifiManagerPlugin.onPause(WifiManagerPlugin.java:116)
at org.apache.cordova.PluginManager.onPause(PluginManager.java:211)
at org.apache.cordova.CordovaWebViewImpl.handlePause(CordovaWebViewImpl.java:431)
at org.apache.cordova.CordovaActivity.onPause(CordovaActivity.java:245)
at android.app.Activity.performPause(Activity.java:7033)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1339)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4585)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4558)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4533)
at android.app.ActivityThread.access$1300(ActivityThread.java:222)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7237)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by rporta** [comment]
Spanish

Solucion temporal,

ir al siguiente archivo :
app/platforms/android/app/src/main/java/dk/kapetanovic/wifimanager/WifiManagerPlugin.java

modificar en el method WifiManagerPlugin.onPause();

comentar :

//cordova.getActivity().unregisterReceiver(broadcastReceiver);

posteriormente desplegar la app en la application
